// vm2/opcodes.mjs
// Complete opcode dispatch table of the register-VM interpreter `w4(i4,x1,w1)`
// found in nzl2_vm.lua (single-line obfuscated Lua/Luau). Transcribed 1:1 from
// the actual source; the dispatch chain has 116 `k1==<n>` branches and NO
// default/else branch (unknown opcodes fall through as silent no-ops).
//
// ── Variable mapping (Lua → canonical names used in `sem`) ──────────────────
//   N4  → R     register file. Args are loaded with N4[l1-1]=x1[l1], so the
//               first argument lands in R[0]; R[0] is also the slot the decoy
//               opcodes read. Varargs beyond proto.G1 go to VA.
//   u4  → A     target register (instruction field J4)
//   p4  → B     operand 1 (field T4) — register index OR small immediate
//   L4  → C     operand 2 (field l4) — register index OR small immediate
//   m4  → sBx   signed int32 operand (field Q4), used for constants & jumps
//   f1  → K     constants of current proto: Lua `f1[m4+1]` is written K[sBx]
//               (constants are conceptually 0-based through the +1 shift)
//   B1  → ENV   getfenv() or _G
//   D4  → PC    program counter into i4.o2 (1-based list). It is incremented
//               once per dispatch BEFORE the branch body runs. A branch doing
//               `D4=D4+m4` therefore lands on instruction (current+1+sBx);
//               `D4=D4-m4` (opcode 41) lands on (current+1-sBx).
//   M4  → VA    varargs array (Lua 1-based: VA[1] is the first vararg)
//   w1  → ups   upvalue cells of the running frame: ups[i] = [cellTable, idx]
//               (Lua {G2[1],G2[2]}); read = cellTable[idx], write = same.
//   i4  → proto current proto container: .o2 instructions, .H1 constants,
//               .T1 child protos (1-based), .G1 param count, .M1 upvalue descs
//   E1  → unpack (table.unpack or unpack)
//
// Instruction encoding (see deserializer W4 in nzl2_vm.lua): 8 bytes per
// instruction — opcode, A, B, C (one byte each) + signed-int32 sBx (LE).
//
// ── Caveats found while transcribing ───────────────────────────────────────
// * `string.W1`, `string.S1`, `string.C2`, `string.V1`, `string.m2`,
//   `math.z2`, `math.h2`, `math.k2`, `math.y2`, `math.M2` are NEVER defined
//   anywhere in nzl2_vm.lua. The 10 opcodes that call them (68, 46, 52, 85,
//   112, 163, 176, 189, 243, 244) would raise "attempt to call a nil value"
//   if dispatched — they are decoys, or the host environment is expected to
//   inject these renamed stdlib aliases (e.g. string.m2 behaves exactly like
//   string.find(s, pat, init, plain)).
// * R[A]===K[sBx] etc. below use JS `===` loosely for Lua `==` (both compare
//   by value for strings/numbers, by identity for tables).

export const OPCODES = {
  27: {
    mnemonic: 'EQ_K',
    sem: 'if (R[A] == K[sBx]) PC += 1',
    jump: 'cond-fwd',
    dead: false,
    note: 'Conditional skip of the NEXT instruction (auto-increment already applied, so equality makes next = current+2 instead of current+1). Classic Lua 5.1 EQ/test-and-skip.',
  },
  163: {
    mnemonic: 'STR_W1',
    sem: 'R[A] = string.W1(R[B])',
    jump: null,
    dead: false,
    note: 'string.W1 is NOT defined anywhere in the file — nil-call trap unless the host injects it. One-argument renamed string function (upper/lower/reverse style).',
  },
  176: {
    mnemonic: 'STR_S1',
    sem: 'R[A] = string.S1(R[B], R[C])',
    jump: null,
    dead: false,
    note: 'string.S1 NOT defined in the file (nil-call trap). Two-argument renamed string function (rep style).',
  },
  225: {
    mnemonic: 'TYPE',
    sem: 'R[A] = type(R[B])',
    jump: null,
    dead: false,
    note: 'Returns the Lua type name string.',
  },
  104: {
    mnemonic: 'SUB_K',
    sem: 'R[A] = R[B] - K[sBx]',
    jump: null,
    dead: false,
    note: 'Subtract constant.',
  },
  14: {
    mnemonic: 'GETUPVAL',
    sem: 'R[A] = ups[B] ? ups[B][0][ups[B][1]] : null',
    jump: null,
    dead: false,
    note: 'Upvalue read via cell pair {cellTable, index} (Lua G2[1][G2[2]]). Missing upvalue loads nil.',
  },
  109: {
    mnemonic: 'TONUM',
    sem: 'R[A] = tonumber(R[B])',
    jump: null,
    dead: false,
    note: 'nil if not convertible.',
  },
  216: {
    mnemonic: 'JMP',
    sem: 'PC += sBx',
    jump: 'fwd',
    dead: false,
    note: 'Unconditional relative forward jump; effective next instruction = current + 1 + sBx.',
  },
  119: {
    mnemonic: 'BYTE',
    sem: 'R[A] = string.byte(R[B], R[C] || 1)',
    jump: null,
    dead: false,
    note: 'Single byte code at position R[C] (default 1).',
  },
  138: {
    mnemonic: 'RETURN',
    sem: 'if (B == 0) return; else return R[A], R[A+1], ..., R[A+B-1]',
    jump: null,
    dead: false,
    note: 'Returns exactly B register values starting at R[A] (built into table e2 then spread via unpack(e2,1,B)). B==0 is a bare `return`. One of only two opcode families that exit the frame (with 174).',
  },
  106: {
    mnemonic: 'LT_K',
    sem: 'R[A] = (R[B] < K[sBx])',
    jump: null,
    dead: false,
    note: 'Store comparison boolean.',
  },
  191: {
    mnemonic: 'GT',
    sem: 'R[A] = (R[B] > R[C])',
    jump: null,
    dead: false,
    note: 'Store comparison boolean.',
  },
  44: {
    mnemonic: 'NOP',
    sem: 'const O1 = R[0]; // discarded',
    jump: null,
    dead: true,
    note: 'Decoy: reads R[0] (first argument slot) into a local that is never used. No observable effect.',
  },
  31: {
    mnemonic: 'LOADK',
    sem: 'R[A] = K[sBx]',
    jump: null,
    dead: false,
    note: 'Load constant (Lua f1[m4+1]).',
  },
  121: {
    mnemonic: 'LOADNIL',
    sem: 'R[A] = null',
    jump: null,
    dead: false,
    note: 'Load single nil (opcode 16 is an exact duplicate).',
  },
  99: {
    mnemonic: 'LT',
    sem: 'R[A] = (R[B] < R[C])',
    jump: null,
    dead: false,
    note: 'Store comparison boolean.',
  },
  73: {
    mnemonic: 'LROTATE',
    sem: 'R[A] = bit32.lrotate(R[B], R[C])',
    jump: null,
    dead: false,
    note: '32-bit left rotate.',
  },
  85: {
    mnemonic: 'STR_C2',
    sem: 'R[A] = string.C2(R[B], R[C])',
    jump: null,
    dead: false,
    note: 'string.C2 NOT defined in the file (nil-call trap). Renamed two-argument string function.',
  },
  48: {
    mnemonic: 'FLOOR',
    sem: 'R[A] = math.floor(R[B])',
    jump: null,
    dead: false,
    note: '',
  },
  4: {
    mnemonic: 'SETTABLE',
    sem: 'R[A][R[B]] = R[C]',
    jump: null,
    dead: false,
    note: 'Table in R[A], key in R[B], value in R[C] (opcode 141 is an exact duplicate).',
  },
  39: {
    mnemonic: 'CONCAT_TOSTR',
    sem: "let s = ''; for (let t = B; t <= C; t++) s += tostring(R[t]); R[A] = s",
    jump: null,
    dead: false,
    note: 'Join of tostring() over an absolute register range R[B..C] (B and C are register indices, not values).',
  },
  183: {
    mnemonic: 'GETTABLE_K',
    sem: 'R[A] = R[B][K[sBx]]',
    jump: null,
    dead: false,
    note: 'Constant-key table read (opcode 209 is an exact duplicate).',
  },
  243: {
    mnemonic: 'MATH_Z2',
    sem: 'R[A] = math.z2(R[B], R[C])',
    jump: null,
    dead: false,
    note: 'math.z2 NOT defined in the file (nil-call trap). Renamed two-argument math function.',
  },
  17: {
    mnemonic: 'BOR',
    sem: 'R[A] = bit32.bor(R[B], R[C])',
    jump: null,
    dead: false,
    note: '',
  },
  179: {
    mnemonic: 'EQ_KR',
    sem: 'R[A] = (R[B] == K[sBx])',
    jump: null,
    dead: false,
    note: 'Stores the equality boolean into R[A] — unlike opcode 27 which SKIPS the next instruction instead of storing.',
  },
  134: {
    mnemonic: 'TOSTR',
    sem: 'R[A] = tostring(R[B])',
    jump: null,
    dead: false,
    note: '',
  },
  164: {
    mnemonic: 'NOP',
    sem: 'const J1 = R[0]; // discarded',
    jump: null,
    dead: true,
    note: 'Decoy: reads R[0] into an unused local.',
  },
  10: {
    mnemonic: 'LSHIFT',
    sem: 'R[A] = bit32.lshift(R[B], R[C])',
    jump: null,
    dead: false,
    note: '',
  },
  148: {
    mnemonic: 'GETTABLE',
    sem: 'R[A] = R[B][R[C]]',
    jump: null,
    dead: false,
    note: 'Register-key table read (opcode 29 is an exact duplicate).',
  },
  51: {
    mnemonic: 'UNM',
    sem: 'R[A] = -R[B]',
    jump: null,
    dead: false,
    note: '',
  },
  68: {
    mnemonic: 'SPLIT',
    sem: "const parts = []; const s = R[B]; const sep = tostring(R[C] ?? ','); let i = 1;\nwhile (true) { const f = string.m2(s, sep, i, /*plain=*/true); /* == string.find */\n  if (f == null) { parts.push(string.sub(s, i)); break; }\n  parts.push(string.sub(s, i, f - 1)); i = f + #sep; }\nR[A] = parts",
    jump: null,
    dead: false,
    note: 'string.find(plain=true)-based split of R[B] by delimiter tostring(R[C] or ",") into a 1-based array. string.m2 is NOT defined in the file (nil-call trap).',
  },
  33: {
    mnemonic: 'MUL',
    sem: 'R[A] = R[B] * R[C]',
    jump: null,
    dead: false,
    note: '',
  },
  208: {
    mnemonic: 'ADD_K',
    sem: 'R[A] = R[B] + K[sBx]',
    jump: null,
    dead: false,
    note: '',
  },
  45: {
    mnemonic: 'ERROR',
    sem: 'error(tostring(R[A]))',
    jump: null,
    dead: false,
    note: 'Raises with the stringified value already in R[A] (not R[B]).',
  },
  80: {
    mnemonic: 'GETMETATABLE',
    sem: 'R[A] = getmetatable(R[B]) || null',
    jump: null,
    dead: false,
    note: 'Probes the global getmetatable defensively (works even if sandbox nils it).',
  },
  182: {
    mnemonic: 'LOADTRUE',
    sem: 'R[A] = (#tostring(type(nil)) == 3)',
    jump: null,
    dead: false,
    note: 'Constant-fold trick: tostring(type(nil)) == "nil" has length 3 → always true.',
  },
  153: {
    mnemonic: 'LOADB',
    sem: 'R[A] = (B != 0)',
    jump: null,
    dead: false,
    note: 'Loads a boolean immediate carried in the B operand field itself.',
  },
  209: {
    mnemonic: 'GETTABLE_K',
    sem: 'R[A] = R[B][K[sBx]]',
    jump: null,
    dead: false,
    note: 'EXACT duplicate of opcode 183 (same body).',
  },
  196: {
    mnemonic: 'LEN',
    sem: 'R[A] = #R[B]',
    jump: null,
    dead: false,
    note: 'Length operator (opcode 144 is an exact duplicate).',
  },
  52: {
    mnemonic: 'MATH_H2',
    sem: 'R[A] = math.h2(R[B])',
    jump: null,
    dead: false,
    note: 'math.h2 NOT defined in the file (nil-call trap). Renamed one-argument math function (abs/sqrt style).',
  },
  213: {
    mnemonic: 'BOOL',
    sem: 'R[A] = !!R[B]',
    jump: null,
    dead: false,
    note: '`not not` truthiness normalization (keeps falsy nil/false as false).',
  },
  26: {
    mnemonic: 'SETTABLE_K',
    sem: 'R[A][K[sBx]] = R[B]',
    jump: null,
    dead: false,
    note: 'Constant-key table write (opcode 165 is an exact duplicate). Value comes from R[B].',
  },
  60: {
    mnemonic: 'TESTF',
    sem: 'if (!R[A]) PC += sBx',
    jump: 'cond-fwd',
    dead: false,
    note: 'Conditional jump when R[A] is falsy (nil/false). Effective target = current + 1 + sBx.',
  },
  170: {
    mnemonic: 'NOP',
    sem: 'const F1 = null; // unused',
    jump: null,
    dead: true,
    note: 'Decoy: binds a local to nil, never used.',
  },
  189: {
    mnemonic: 'STR_V1',
    sem: 'R[A] = string.V1(R[B])',
    jump: null,
    dead: false,
    note: 'string.V1 NOT defined in the file (nil-call trap). Renamed one-argument string function.',
  },
  255: {
    mnemonic: 'LE',
    sem: 'R[A] = (R[B] <= R[C])',
    jump: null,
    dead: false,
    note: '',
  },
  234: {
    mnemonic: 'LOADI',
    sem: 'R[A] = (B >= 128) ? B - 256 : B',
    jump: null,
    dead: false,
    note: 'Small signed integer immediate carried in the B byte with sign extension at 128.',
  },
  144: {
    mnemonic: 'LEN',
    sem: 'R[A] = #R[B]',
    jump: null,
    dead: false,
    note: 'EXACT duplicate of opcode 196 (same body).',
  },
  242: {
    mnemonic: 'BNOT',
    sem: 'R[A] = bit32.bnot(R[B])',
    jump: null,
    dead: false,
    note: '',
  },
  156: {
    mnemonic: 'SWAP',
    sem: '[R[A], R[B]] = [R[B], R[A]]',
    jump: null,
    dead: false,
    note: 'Register swap.',
  },
  133: {
    mnemonic: 'GETGLOBAL',
    sem: 'R[A] = ENV[K[sBx]]',
    jump: null,
    dead: false,
    note: 'ENV = getfenv() or _G captured once per frame.',
  },
  9: {
    mnemonic: 'INFLOOP',
    sem: 'while (true) {}',
    jump: null,
    dead: false,
    note: 'TRAP: empty infinite loop — hangs the thread if ever dispatched. Presumably never emitted by the encoder (anti-tamper). Not marked dead because it HAS an observable effect.',
  },
  29: {
    mnemonic: 'GETTABLE',
    sem: 'R[A] = R[B][R[C]]',
    jump: null,
    dead: false,
    note: 'EXACT duplicate of opcode 148 (same body).',
  },
  59: {
    mnemonic: 'DIV_K',
    sem: 'R[A] = R[B] / K[sBx]',
    jump: null,
    dead: false,
    note: '',
  },
  194: {
    mnemonic: 'SELF',
    sem: 'R[A + 1] = R[B]; R[A] = R[B][R[C]]',
    jump: null,
    dead: false,
    note: 'Method-call setup: object duplicated into R[A+1], method fetched into R[A].',
  },
  66: {
    mnemonic: 'GE',
    sem: 'R[A] = (R[B] >= R[C])',
    jump: null,
    dead: false,
    note: '',
  },
  205: {
    mnemonic: 'NOP',
    sem: 'const h1 = null; // unused',
    jump: null,
    dead: true,
    note: 'Decoy: binds a local to nil, never used.',
  },
  244: {
    mnemonic: 'MATH_K2',
    sem: 'R[A] = math.k2(R[B])',
    jump: null,
    dead: false,
    note: 'math.k2 NOT defined in the file (nil-call trap). Renamed one-argument math function.',
  },
  128: {
    mnemonic: 'NE',
    sem: 'R[A] = (R[B] != R[C])',
    jump: null,
    dead: false,
    note: '',
  },
  112: {
    mnemonic: 'MATH_Y2',
    sem: 'R[A] = math.y2(R[B], R[C])',
    jump: null,
    dead: false,
    note: 'math.y2 NOT defined in the file (nil-call trap). Renamed two-argument math function.',
  },
  145: {
    mnemonic: 'BAND',
    sem: 'R[A] = bit32.band(R[B], R[C])',
    jump: null,
    dead: false,
    note: '',
  },
  237: {
    mnemonic: 'VARARG',
    sem: 'if (B == 1) R[A] = VA[1]; else { R[A] = {}; for (let t = 1; t <= #VA; t++) R[A][t] = VA[t]; }',
    jump: null,
    dead: false,
    note: 'B==1 loads just the FIRST vararg; otherwise packs ALL varargs of the frame into a fresh table. VA (M4) is the 1-based varargs array.',
  },
  116: {
    mnemonic: 'NOT',
    sem: 'R[A] = !R[B]',
    jump: null,
    dead: false,
    note: '',
  },
  231: {
    mnemonic: 'REMOVE',
    sem: 'const t = R[B]; const i = R[C] || #t; const v = t[i];\nfor (let k = i; k <= #t - 1; k++) t[k] = t[k + 1];\nt[#t] = null; R[A] = v',
    jump: null,
    dead: false,
    note: 'Inlined table.remove(t, pos) with pos = R[C] or #t (1-based); returns the removed value.',
  },
  200: {
    mnemonic: 'UNPACK',
    sem: 'const t = R[C]; for (let i = 0; i <= B - 1; i++) R[A + i] = t[i + 1]',
    jump: null,
    dead: false,
    note: 'Spreads the first B entries of table R[C] into R[A..A+B-1] (argument loading / table.unpack into regs). B==0 is a no-op.',
  },
  113: {
    mnemonic: 'MOD',
    sem: 'R[A] = R[B] % R[C]',
    jump: null,
    dead: false,
    note: 'Lua modulo semantics.',
  },
  96: {
    mnemonic: 'NOP',
    sem: 'const P1 = null; // unused',
    jump: null,
    dead: true,
    note: 'Decoy: binds a local to nil, never used.',
  },
  166: {
    mnemonic: 'RSHIFT',
    sem: 'R[A] = bit32.rshift(R[B], R[C])',
    jump: null,
    dead: false,
    note: '',
  },
  165: {
    mnemonic: 'SETTABLE_K',
    sem: 'R[A][K[sBx]] = R[B]',
    jump: null,
    dead: false,
    note: 'EXACT duplicate of opcode 26 (same body).',
  },
  88: {
    mnemonic: 'SETLIST',
    sem: 'for (let t = 1; t <= B; t++) R[A][C + t] = R[A + t]',
    jump: null,
    dead: false,
    note: 'Flushes B values R[A+1..A+B] into table R[A] at indices C+1..C+B — C is the 0-based base index of the array block.',
  },
  93: {
    mnemonic: 'TFORLOOP',
    sem: 'if (R[A + 3] != null) { R[A + 2] = R[A + 3]; PC += sBx; }',
    jump: 'cond-back',
    dead: false,
    note: 'Generic-for loop close: while the iterator state R[A+3] is non-nil, copy it into the visible variable R[A+2] and jump back to the loop body (sBx negative back-edge).',
  },
  146: {
    mnemonic: 'NOP',
    sem: 'const B4 = #tostring(math.floor(1)) + #R[0]; // discarded',
    jump: null,
    dead: true,
    note: 'Decoy constant-fold: #tostring(math.floor(1)) is always 1; result B4 unused. CAVEAT: `#R[0]` raises a runtime error if R[0] is nil (or a non-lengthable value), so this doubles as an error trap.',
  },
  81: {
    mnemonic: 'NOP',
    sem: 'const N1 = R[0]; // discarded',
    jump: null,
    dead: true,
    note: 'Decoy: reads R[0] into an unused local.',
  },
  83: {
    mnemonic: 'EQ',
    sem: 'R[A] = (R[B] == R[C])',
    jump: null,
    dead: false,
    note: '',
  },
  61: {
    mnemonic: 'TESTT',
    sem: 'if (R[A]) PC += sBx',
    jump: 'cond-fwd',
    dead: false,
    note: 'Conditional jump when R[A] is truthy. Effective target = current + 1 + sBx.',
  },
  252: {
    mnemonic: 'SETMETATABLE',
    sem: 'const f = setmetatable; if (f) f(R[A], R[B])',
    jump: null,
    dead: false,
    note: 'Defensive global probe; return value (the table) is discarded.',
  },
  219: {
    mnemonic: 'AND',
    sem: 'R[A] = R[B] && R[C]',
    jump: null,
    dead: false,
    note: 'Lua `and` value semantics: R[B] if falsy, else R[C].',
  },
  43: {
    mnemonic: 'LOADFALSE',
    sem: 'R[A] = (#tostring(type(nil)) == 4)',
    jump: null,
    dead: false,
    note: 'Constant-fold trick: "nil" has length 3, so == 4 is always false.',
  },
  161: {
    mnemonic: 'SETUPVAL',
    sem: 'if (ups[B]) ups[B][0][ups[B][1]] = R[A]',
    jump: null,
    dead: false,
    note: 'Upvalue write through the {cellTable, index} pair (Lua G2[1][G2[2]]=R[A]).',
  },
  203: {
    mnemonic: 'CLEAR',
    sem: 'for (let t = A; t <= A + B; t++) R[t] = null',
    jump: null,
    dead: false,
    note: 'Nil-out a contiguous register window R[A..A+B] (B+1 registers — inclusive upper bound).',
  },
  107: {
    mnemonic: 'POW',
    sem: 'R[A] = R[B] ^ R[C]',
    jump: null,
    dead: false,
    note: '',
  },
  16: {
    mnemonic: 'LOADNIL',
    sem: 'R[A] = null',
    jump: null,
    dead: false,
    note: 'EXACT duplicate of opcode 121 (same body).',
  },
  214: {
    mnemonic: 'CLOSURE',
    sem: "const k = K[sBx];\nif (type(k) == 'table' && k.z1 != null) {  // constant is a proto ref {z1: idx}\n  const child = proto.T1[k.z1 + 1];       // child protos list is 1-based\n  const upsv = [];                         // g1: upvalue cells for the new closure\n  if (child.M1) for (let j = 1; j <= #child.M1; j++) {\n    const d = child.M1[j];                 // {R1: bool, d2: index}\n    upsv[j - 1] = d.R1 ? [R, d.d2]         // R1: OPEN cell aliasing THIS frame's register array at index d2\n                       : (ups ? ups[d.d2] : null); // else inherit parent's upvalue cell\n  }\n  R[A] = (...args) => w4(child, args, upsv);\n}",
    jump: null,
    dead: false,
    note: 'Creates a closure over child proto referenced by constant K[sBx] ({z1 = childIndex}). If K[sBx] is not a proto table, the opcode silently does nothing (R[A] untouched). Note R1-captures alias the register array itself, so parent register writes are visible through the upvalue.',
  },
  125: {
    mnemonic: 'IDIV',
    sem: 'R[A] = math.floor(R[B] / R[C])',
    jump: null,
    dead: false,
    note: 'Floor integer division.',
  },
  100: {
    mnemonic: 'ADD',
    sem: 'R[A] = R[B] + R[C]',
    jump: null,
    dead: false,
    note: '',
  },
  185: {
    mnemonic: 'SUB',
    sem: 'R[A] = R[B] - R[C]',
    jump: null,
    dead: false,
    note: '',
  },
  136: {
    mnemonic: 'MOVE',
    sem: 'R[A] = R[B]',
    jump: null,
    dead: false,
    note: 'EXACT duplicate of opcode 91 (same body).',
  },
  157: {
    mnemonic: 'SETGLOBAL',
    sem: 'ENV[K[sBx]] = R[A]',
    jump: null,
    dead: false,
    note: 'Value taken from R[A] (not R[B]).',
  },
  91: {
    mnemonic: 'MOVE',
    sem: 'R[A] = R[B]',
    jump: null,
    dead: false,
    note: '',
  },
  84: {
    mnemonic: 'RROTATE',
    sem: 'R[A] = bit32.rrotate(R[B], R[C])',
    jump: null,
    dead: false,
    note: '',
  },
  172: {
    mnemonic: 'ASSERT',
    sem: 'if (R[A] === false || R[A] == null) error(tostring(R[B]))',
    jump: null,
    dead: false,
    note: 'Asserts R[A] is neither false nor nil, else raises with tostring(R[B]).',
  },
  24: {
    mnemonic: 'CONCAT',
    sem: "let sep = R[C]; if (type(sep) != 'string') sep = ''; R[A] = table.concat(R[B], sep)",
    jump: null,
    dead: false,
    note: 'table.concat join of array R[B] with separator R[C] (non-string separator coerced to the empty string).',
  },
  160: {
    mnemonic: 'MOD_K',
    sem: 'R[A] = R[B] % K[sBx]',
    jump: null,
    dead: false,
    note: '',
  },
  245: {
    mnemonic: 'NEWTABLE',
    sem: 'R[A] = {}',
    jump: null,
    dead: false,
    note: '',
  },
  150: {
    mnemonic: 'SUBSTR',
    sem: 'R[A] = string.sub(R[B], R[C], R[C + 1] || -1)',
    jump: null,
    dead: false,
    note: 'Substring from R[C] to R[C+1] (default -1 = rest). Reads a FOURTH register (C+1) beyond the usual operands.',
  },
  155: {
    mnemonic: 'DIV',
    sem: 'R[A] = R[B] / R[C]',
    jump: null,
    dead: false,
    note: '',
  },
  162: {
    mnemonic: 'BXOR',
    sem: 'R[A] = bit32.bxor(R[B], R[C])',
    jump: null,
    dead: false,
    note: '',
  },
  72: {
    mnemonic: 'INDEXOF',
    sem: 'let f = null; for (let t = 1; t <= #R[B]; t++) if (R[B][t] == R[C]) { f = t; break; } R[A] = f',
    jump: null,
    dead: false,
    note: 'Linear search of value R[C] in array R[B]; stores the 1-based index or nil.',
  },
  248: {
    mnemonic: 'OR',
    sem: 'R[A] = R[B] || R[C]',
    jump: null,
    dead: false,
    note: 'Lua `or` value semantics.',
  },
  8: {
    mnemonic: 'MUL_K',
    sem: 'R[A] = R[B] * K[sBx]',
    jump: null,
    dead: false,
    note: '',
  },
  132: {
    mnemonic: 'APPEND_BC',
    sem: 'R[B][#R[B] + 1] = R[C]',
    jump: null,
    dead: false,
    note: 'Append value R[C] to the array in R[B] (table operand in B — mirrored variant of opcode 15).',
  },
  15: {
    mnemonic: 'APPEND',
    sem: 'R[A][#R[A] + 1] = R[B]',
    jump: null,
    dead: false,
    note: 'Append value R[B] to the array in R[A] (table constructor push).',
  },
  50: {
    mnemonic: 'CALL2',
    sem: 'const res = [R[A](R[A + 1], R[A + 2])];\nfor (let j = 1; j <= B; j++) R[A + 2 + j] = res[j];',
    jump: null,
    dead: false,
    note: 'Call variant: ALWAYS exactly two args R[A+1], R[A+2]. B return values are stored ABOVE the call window at R[A+3..A+2+B] — the function/arg registers are NOT overwritten.',
  },
  178: {
    mnemonic: 'NOP',
    sem: 'const I1 = R[0]; // discarded',
    jump: null,
    dead: true,
    note: 'Decoy: reads R[0] into an unused local.',
  },
  174: {
    mnemonic: 'TAILCALL',
    sem: 'const args = [R[A + 1], ..., R[A + B - 1]]; // B-1 args\nreturn R[A](...args); // via unpack(args, 1, B-1)',
    jump: null,
    dead: false,
    note: 'Call-and-return-all: exits the frame returning every result of R[A](R[A+1..A+B-1]). B==0 → zero args.',
  },
  253: {
    mnemonic: 'CHARJOIN',
    sem: "let s = ''; for (let t = B; t <= C; t++) s += string.char(R[t]); R[A] = s",
    jump: null,
    dead: false,
    note: 'Builds a string from byte values in the absolute register range R[B..C].',
  },
  141: {
    mnemonic: 'SETTABLE',
    sem: 'R[A][R[B]] = R[C]',
    jump: null,
    dead: false,
    note: 'EXACT duplicate of opcode 4 (same body).',
  },
  46: {
    mnemonic: 'MATH_M2',
    sem: 'R[A] = math.M2(R[B])',
    jump: null,
    dead: false,
    note: 'math.M2 NOT defined in the file (nil-call trap). Renamed one-argument math function.',
  },
  117: {
    mnemonic: 'SIGN',
    sem: 'const v = R[B]; R[A] = v > 0 ? 1 : (v < 0 ? -1 : 0)',
    jump: null,
    dead: false,
    note: 'Signum.',
  },
  49: {
    mnemonic: 'PACK',
    sem: 'R[A] = {}; for (let t = B; t <= C; t++) R[A][t - B + 1] = R[t]',
    jump: null,
    dead: false,
    note: 'Table constructor: packs the absolute register range R[B..C] into a fresh 1-based array.',
  },
  87: {
    mnemonic: 'FORPREP',
    sem: 'R[A] = R[A] - R[A + 2]; PC += sBx',
    jump: 'fwd',
    dead: false,
    note: 'Numeric-for setup: internal index R[A] -= step R[A+2], then jumps (usually forward) to the loop test opcode 207. Limit lives in R[A+1], visible var in R[A+3].',
  },
  188: {
    mnemonic: 'CALL',
    sem: 'const args = [R[A + 1], ..., R[A + B - 1]]; // B-1 args\nconst res = [R[A](...args)]; // capture all results\nlet want = C - 1; if (want === -1) want = res.length; // C==0 → all\nfor (let j = 1; j <= want; j++) R[A + j - 1] = res[j];',
    jump: null,
    dead: false,
    note: 'General call: B-1 arguments from R[A+1..A+B-1]; C = desired result count + 1 (C==0 takes all). Results OVERWRITE starting at R[A]. Args built into U1 then spread via unpack(U1,1,B-1).',
  },
  41: {
    mnemonic: 'JMP_BACK',
    sem: 'PC -= sBx',
    jump: 'back',
    dead: false,
    note: 'Unconditional relative backward jump; effective next instruction = current + 1 - sBx (loop back-edge counterpart of 216).',
  },
  151: {
    mnemonic: 'LE_K',
    sem: 'R[A] = (R[B] <= K[sBx])',
    jump: null,
    dead: false,
    note: '',
  },
  86: {
    mnemonic: 'NOP',
    sem: 'const Q1 = R[0]; // discarded',
    jump: null,
    dead: true,
    note: 'Decoy: reads R[0] into an unused local.',
  },
  207: {
    mnemonic: 'FORLOOP',
    sem: 'R[A] = R[A] + R[A + 2]; // index += step\nconst step = R[A + 2];\nconst cont = step > 0 ? R[A] <= R[A + 1] : R[A] >= R[A + 1];\nif (cont) { R[A + 3] = R[A]; PC += sBx; }',
    jump: 'cond-back',
    dead: false,
    note: 'Numeric-for step check: increments the internal index by step, compares against limit R[A+1] with direction-aware test, copies the index to visible var R[A+3] and jumps back to the body (sBx negative back-edge) while the loop continues.',
  },
};

// Decoy opcodes whose branch body has no observable effect on VM state.
export const DEAD_OPCODES = [44, 164, 170, 205, 96, 146, 81, 178, 86];

// Number of `k1==<n>` branches in the w4 dispatch chain of nzl2_vm.lua.
export const OP_COUNT = 116;
